apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              resources:
                limits:
                  cpu: "1"
                  memory: 4Gi
                requests:
                  cpu: 250m
                  memory: 2Gi
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure