---
name: ci
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://golangci/golangci-lint:v1.43.0
      with:
        args: golangci-lint run
      env:
        CGO_ENABLED: 0
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.1'
    - name: Print go version
      run: go version
    - name: Run unit tests
      run: go test -cover ./...
